version: '3.10'

services:
  djangoserver:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: mydjango


  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: greeny
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  
  redis:
    image: redis:alpine
    container_name: redisserver


  celery:
    image: celery:alpine
    container_name: celeryserver
    command: celery -A project worker -l info
    volumes:
      - .:/app
    restart: always
    build: 
      context: .
    depends_on:
      - djangoserver
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0


volumes:
  postgres_data:


